// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Esli-KtVE4HpeoNQGXltD7_R75eESjc',
    appId: '1:537476245296:web:a10d81b6f3b64da7214af5',
    messagingSenderId: '537476245296',
    projectId: 'wanna-do-64b08',
    authDomain: 'wanna-do-64b08.firebaseapp.com',
    storageBucket: 'wanna-do-64b08.appspot.com',
    measurementId: 'G-VC0SDDRPD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPhCk8bL4rslDsSElBsb0YDK8FQiFzkg',
    appId: '1:537476245296:android:2d7ed13346ce8953214af5',
    messagingSenderId: '537476245296',
    projectId: 'wanna-do-64b08',
    storageBucket: 'wanna-do-64b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMlHHkWSX9KHGXu88HjyEApum1gtVzdo',
    appId: '1:537476245296:ios:53cacc906488f263214af5',
    messagingSenderId: '537476245296',
    projectId: 'wanna-do-64b08',
    storageBucket: 'wanna-do-64b08.appspot.com',
    iosBundleId: 'com.hst.wannaDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClMlHHkWSX9KHGXu88HjyEApum1gtVzdo',
    appId: '1:537476245296:ios:ebbb37ca6c9a383b214af5',
    messagingSenderId: '537476245296',
    projectId: 'wanna-do-64b08',
    storageBucket: 'wanna-do-64b08.appspot.com',
    iosBundleId: 'com.example.wannaDo.RunnerTests',
  );
}
